---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wakfu.
--- DateTime: 2020/8/18 10:02
---


silk = require("libSKP_SILK_SDK.a")

function get_version()
    local version = silk:get_version()
    print(version)
end

