---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wakfu.
--- DateTime: 2020/8/4 17:58
---

function testSql()
    local luaDbSqLite = require('lua.nativeSql.LuaDb')
    local Builder = require "lua.nativeSql.LuaQuB"

    local c = luaDbSqLite.new()
    local ok, err = c:open('salary.db', { cache = 'shared' })
    if ok then
        local object = Builder.new()
        object:select("*")
        object:from("t_salary")
        res, err = c:query(tostring(object))
        print(res[1].name)
        return { res = res, err = err }
    end
end