---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wakfu.
--- DateTime: 2020/8/1 11:37
---
Orm = {}

function Orm.new(tableName)
    local obj = db_module.new(tableName)
    return obj
end


--*********************go实现的接口api**************************

--获取列表
---@return number|table
function Orm:Rows()
end

function Orm:Tag()
end

function Orm:Insert(table)
end

return Orm


