---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wakfu.
--- DateTime: 2020/8/4 17:58
---
local example = {}
--
local luaDbSqLite = require('lua.db_module.db_module')
local Builder = require "lua.nativeSql.LuaQuB"
local ormDb = luaDbSqLite.new("t_salary")

function example.getList()
    local object = Builder.new()
                          :select("*")
                          :from("t_salary")
                          :where({ department = "实习", social_security = 100 }, "and")
                          :where("`name` = ", "王叔叔", "or")
                          :limit(10, 2)

    local code, tables = ormDb:Raw(tostring(object))
    print(ormDb:Tag(), #tables)

    return code, tables
end

function example.insertCol()
    local object = Builder.new()
                          :insert("t_salary",
            { name = "小明12", department = "实习", social_security = 100 })

    local code, response = ormDb:Exec(tostring(object))
    print(ormDb:Tag(), response)

    print(code, response)
end

return example