---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wakfu.
--- DateTime: 2020/8/4 17:58
---

function testSql()
    local luaDbSqLite = require('lua.db_module.db_module')

    local ormDb = luaDbSqLite.new("t_salary")
    local code, rsp = ormDb:Rows()
    return { code = code, rsp = rsp }
end